#include "draw.h"
#include "gba.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
#include "images/garbage.h"

#include <stdio.h>

#define MIN(x, y) ((x < y) ? x : y)
#define MAX(x, y) ((x < y) ? y : x)

#define CLEAR_COLOR COLOR(0, 12, 5)

static void drawBall(ball_t *ball) {
    int x = FIXED_TO_INT(ball->x);
    int y = FIXED_TO_INT(ball->y);
    int r = FIXED_TO_INT(ball->radius);

    drawRectDMA(x - r, y - r, 2 * r, 2 * r, ball->color);
}

static void undrawBall(ball_t *ball) {
    int x = FIXED_TO_INT(ball->x);
    int y = FIXED_TO_INT(ball->y);
    int r = FIXED_TO_INT(ball->radius);

    // Since these will generally be images/circles, we have to just clear the entire shape
    drawRectDMA(x - r, y - r, 2 * r, 2 * r, CLEAR_COLOR);
}

static void drawCue(ball_t *cue_ball, cue_t *cue) {
    fixed_t sx = cue_ball->x;
    fixed_t sy = cue_ball->y;

    fixed_t ex = cue->x;
    fixed_t ey = cue->y;

    fixed_t slope = FIXED_DIV(ey - sy, ex - sx);

    if (slope < 0) {
        for (fixed_t x = ey; x <= sy; x += FIXED_ONE) {
            fixed_t y = ex + FIXED_MULT(slope, x);

            int xx = FIXED_TO_INT(x);
            int yy = FIXED_TO_INT(y);

            setPixel(xx, yy, cue->color);
        }
    } else {
        for (fixed_t x = sy; x <= ey; x += FIXED_ONE) {
            fixed_t y = sx + FIXED_MULT(slope, x);

            int xx = FIXED_TO_INT(x);
            int yy = FIXED_TO_INT(y);

            setPixel(xx, yy, cue->color);
        }
    }
}

static void undrawCue(ball_t *cue_ball, cue_t *cue) {
    fixed_t sx = cue_ball->x;
    fixed_t sy = cue_ball->y;

    fixed_t ex = cue->x;
    fixed_t ey = cue->y;

    if (sx < ex && sy < ey) {
        drawRectDMA(sx, sy, ex - sx, ey - sy, CLEAR_COLOR);
    } else if (sx < ex && ey < sy) {
        drawRectDMA(sx, ey, ex - sx, sy - ey, CLEAR_COLOR);
    } else if (ex < sx && sy < ey) {
      drawRectDMA(ex, sy, sx - ex, ey - sy, CLEAR_COLOR);
    } else if (ex < sx && ey < sy) {
        drawRectDMA(ex, ey, sx - ex, sy - ey, CLEAR_COLOR);
    }
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(CLEAR_COLOR);

    drawBall(state->cue_ball);
    drawBall(state->other);
    drawCue(state->cue_ball, state->cue);
}

// Draw the title screen
void fullDrawTitleScreen(void) {
    fillScreenDMA(CLEAR_COLOR);

    drawCenteredString(15, 15, WIDTH - 30, 25, "Welcome to GBA 8Ball!", BLACK);
    drawCenteredString(15, 40, WIDTH - 30, 25, "Press any button to start!", BLACK);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // Undraw balls
    undrawBall(state->cue_ball);
    undrawBall(state->other);
    undrawCue(state->cue_ball, state->cue);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    drawBall(state->cue_ball);
    drawBall(state->other);
    drawCue(state->cue_ball, state->cue);
}
