#include "draw.h"
#include "gba.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
#include "images/garbage.h"

#include <stdio.h>

#define MIN(x, y) ((x < y) ? x : y)
#define MAX(x, y) ((x < y) ? y : x)

#define CLEAR_COLOR COLOR(0, 12, 5)

static void drawBall(ball_t *ball) {
    int x = FIXED_TO_INT(ball->x);
    int y = FIXED_TO_INT(ball->y);
    int r = FIXED_TO_INT(ball->radius);

    // Don't draw if the balls are off screen
    if (x - r >= 0 && x - r < WIDTH && y - r >= 0 && y - r < HEIGHT)
        drawRectDMA(x - r, y - r, 2 * r, 2 * r, ball->color);
}

static void undrawBall(ball_t *ball) {
    int x = FIXED_TO_INT(ball->x);
    int y = FIXED_TO_INT(ball->y);
    int r = FIXED_TO_INT(ball->radius);

    // Since these will generally be images/circles, we have to just clear the entire shape
    drawRectDMA(x - r, y - r, 2 * r, 2 * r, CLEAR_COLOR);
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(CLEAR_COLOR);

    UNUSED(drawBall);
    UNUSED(undrawBall);
    UNUSED(state);
}

// Draw the title screen
void fullDrawTitleScreen(void) {
    fillScreenDMA(CLEAR_COLOR);

    drawCenteredString(15, 15, WIDTH - 30, 25, "Welcome to Ball in Hand!", BLACK);
    drawCenteredString(15, 40, WIDTH - 30, 25, "Press any button to start!", BLACK);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    UNUSED(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    UNUSED(state);
}

void updateSprites(AppState *state, OBJ_ATTR *buffer) {
    // buffer layout = cue ball, 1 .. 15, (AFFINE) cue stick
    obj_set_pos(&buffer[0], state->cue_ball->x, state->cue_ball->y);
    obj_set_pos(&buffer[8], state->other->x, state->other->y);
}
