#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "sprites/sprites.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    TITLE_SCREEN,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

#define INIT_SPRITE(LOCATION, NAME) \
    (LOCATION) = (OBJ_ATTR) { \
        .attr0 = (s16) (ATTR0_Y(0) | ATTR0_REG | ATTR0_BLEND | ATTR0_4BPP | NAME##_BALL_SPRITE_SHAPE), \
        .attr1 = (s16) (ATTR1_X(0) | NAME##_BALL_SPRITE_SIZE), \
        .attr2 = (s16) (ATTR2_ID(NAME##_BALL_ID) | ATTR2_PALBANK(NAME##_BALL_PALETTE_ID)) \
    };

void init_objects(void) {
    OBJ_ATTR *oballs = &obj_buffer[0];

    INIT_SPRITE(oballs[0], CUE);
    INIT_SPRITE(oballs[1], ONE);
    INIT_SPRITE(oballs[2], TWO);
    INIT_SPRITE(oballs[3], THREE);
    INIT_SPRITE(oballs[4], FOUR);
    INIT_SPRITE(oballs[5], FIVE);
    INIT_SPRITE(oballs[6], SIX);
    INIT_SPRITE(oballs[7], SEVEN);
    INIT_SPRITE(oballs[8], EIGHT);
    INIT_SPRITE(oballs[9], NINE);
    INIT_SPRITE(oballs[10], TEN);
    INIT_SPRITE(oballs[11], ELEVEN);
    INIT_SPRITE(oballs[12], TWELVE);
    INIT_SPRITE(oballs[13], THIRTEEN);
    INIT_SPRITE(oballs[14], FOURTEEN);
    INIT_SPRITE(oballs[15], FIFTEEN);

    // Show the cue ball & 8 ball
    obj_unhide(&oballs[0]);
    obj_unhide(&oballs[8]);

    OBJ_AFFINE *ocue = (OBJ_AFFINE *) &obj_buffer[16];
    OBJ_ATTR *ocue_attr = (OBJ_ATTR *) &ocue->fill0[0];
    *ocue_attr = (OBJ_ATTR) {
        .attr0 = (ATTR0_Y(0) | ATTR0_REG | ATTR0_BLEND | ATTR0_4BPP | CUE_SPRITE_SHAPE),
        .attr1 = (ATTR1_X(0) | CUE_SPRITE_SIZE),
        .attr2 = (ATTR2_ID(CUE_ID) | ATTR2_PALBANK(CUE_PALETTE_ID))
    };
    ocue->pa = 0;
    ocue->pb = 0;
    ocue->pc = 0;
    ocue->pd = 0;
}

int main(void) {
    // Copy tiles & palettes for sprites into object memory
    memcpy(&tile_mem[5][0], sprites, SPRITES_SIZE);
    memcpy(pal_obj_mem, sprites_palette, SPRITES_PALETTE_SIZE);

    oam_init(obj_buffer, 128);

    REG_DISPCNT = MODE3 | BG2_ENABLE | SPRITES_ENABLE | SPRITES_DIMENSION_TYPE;

    init_objects();

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the start state here.
                fullDrawTitleScreen();
                
                state = TITLE_SCREEN;
                break;
            case TITLE_SCREEN:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.
                if (KEY_JUST_PRESSED(ANY_KEY, currentButtons, previousButtons)) {
                    state = APP_INIT;
                }
                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);
                updateSprites(&currentAppState, obj_buffer);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                // 16 balls (obj) + 1 cue (affine obj)
                oam_copy(oam_mem, obj_buffer, 16 + 4);

                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);
                updateSprites(&nextAppState, obj_buffer);

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                // Undraw the previous state
                undrawAppState(&currentAppState);

                // Draw the current state
                drawAppState(&nextAppState);

                // 16 balls (obj) + 1 cue (affine obj)
                oam_copy(oam_mem, obj_buffer, 16 + 4);

                // Free the previous state
                cleanupAppState(&currentAppState);

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver) {
                    state = APP_EXIT;
                }

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the exit / gameover screen

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen

                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
